// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngattuwuymzzmbomnqah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nYXR0dXd1eW16em1ib21ucWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTAzNDcsImV4cCI6MjA2OTg4NjM0N30.ZjJM-y_OKwJbZ34ijL_WMz6v53aEaR_ZGHpS1q8ZX48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});